### ISSUE TITLE
Editing odt file

### ISSUE THREAD

**Issue by xian555** [gutschke/pdf2odt#5]
Hi
This tool you wrote is the best tool I've found, including online, in that it translates perfectly pdf content to an odt format.  However the text is a monolithic block that I'm unable to edit, as if it was a locked picture:  I can add text, and the new text appears behind this block.  How to edit the odt produced file?

Thanks,

Chrisitian

**Comment by gutschke** [comment]
You understand correctly, when you described things as a "monolithic block". That's exactly how it works. It converts the PDF file to an image that is used as the background of the page in the ODT file. You can then use LibreOffice to write on top of this image. In most cases, that's what people need, when they want to edit PDF files. They just need to add annotations or maybe a signature or two.

In principle, you can also erase information from the image, but that is a little more difficult to do. You'd have to open the ODT file with "unzip", edit the image files with a graphics editor, and then reassemble the image files into an ODT using pdf2odt. I find, I have to do this extremely rarely; so, there is no automated workflow for it.

Full character recognition is explicitly outside of the scope of this program. So, unfortunately, you won't be able to do arbitrary edits of the PDF document.
